import { getSupabaseAdmin } from './supabaseAdmin.js';

const htmlEscape = (value = '') => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&#039;');

export const objectiveUrl = (req, objectiveId, tab = 'messages') => {
  const host = process.env.APP_BASE_URL
    || (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : '')
    || `${req.headers['x-forwarded-proto'] || 'https'}://${req.headers.host}`;
  const url = new URL(host);
  url.searchParams.set('page', 'objectives');
  url.searchParams.set('objective', objectiveId);
  if (tab !== 'messages') url.searchParams.set('tab', tab);
  return url.toString();
};

export const notificationAllowsEmail = (prefs, type) => {
  if (prefs && prefs.email_enabled === false) return false;
  if (type === 'comment' || type === 'mention') return prefs?.comment_notifications !== false;
  if (type === 'assignment' || type === 'delegation') return prefs?.delegation_alerts !== false;
  if (type === 'due_soon') return prefs?.due_reminders !== false;
  if (type === 'overdue') return prefs?.overdue_alerts !== false;
  if (type === 'blocker' || type === 'at_risk') return prefs?.blocker_alerts !== false;
  return true;
};

export const sendLoggedEmail = async ({ userId, objectiveId, type, dedupeKey, to, subject, html }) => {
  const supabase = getSupabaseAdmin();
  const { data: logRow, error: insertError } = await supabase
    .from('email_delivery_log')
    .insert({
      user_id: userId || null,
      objective_id: objectiveId || null,
      notification_type: type,
      dedupe_key: dedupeKey,
      recipient: to,
      subject,
      status: 'queued',
    })
    .select()
    .single();

  if (insertError) {
    if (/duplicate key|unique/i.test(insertError.message || '')) return { deduped: true };
    throw insertError;
  }

  const resendKey = process.env.RESEND_API_KEY;
  if (!resendKey) {
    await supabase.from('email_delivery_log').update({
      status: 'skipped_no_provider',
      error: 'RESEND_API_KEY is not configured.',
    }).eq('id', logRow.id);
    return { skipped: true };
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${resendKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: process.env.EMAIL_FROM || 'SandPro OMP <onboarding@resend.dev>',
      to,
      subject,
      html,
    }),
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    await supabase.from('email_delivery_log').update({
      status: 'failed',
      error: payload.message || `Resend HTTP ${response.status}`,
    }).eq('id', logRow.id);
    return { failed: true, error: payload.message || `Resend HTTP ${response.status}` };
  }

  await supabase.from('email_delivery_log').update({
    status: 'sent',
    provider_id: payload.id || null,
    sent_at: new Date().toISOString(),
  }).eq('id', logRow.id);
  return { sent: true, id: payload.id };
};

export const buildNotificationEmail = ({ title, preheader, body, detailLabel = '', detailBody = '', ctaUrl, ctaLabel = 'Open in SandPro OMP' }) => `
  <div style="font-family:Arial,sans-serif;line-height:1.5;color:#111827;max-width:620px;margin:0 auto;padding:24px">
    <div style="font-weight:800;color:#ff7f02;font-size:18px;margin-bottom:20px">SandPro OMP</div>
    <div style="display:none;max-height:0;overflow:hidden">${htmlEscape(preheader || title)}</div>
    <h1 style="font-size:22px;margin:0 0 12px">${htmlEscape(title)}</h1>
    <p style="font-size:15px;color:#374151;margin:0 0 20px;white-space:pre-line">${htmlEscape(body)}</p>
    ${detailBody ? `
      <div style="border:1px solid #E5E7EB;border-left:4px solid #ff7f02;border-radius:10px;background:#FFF7ED;padding:14px 16px;margin:0 0 20px">
        <div style="font-size:12px;font-weight:800;color:#9A3412;text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px">${htmlEscape(detailLabel || 'Message')}</div>
        <div style="font-size:15px;color:#1F2937;white-space:pre-line">${htmlEscape(detailBody)}</div>
      </div>
    ` : ''}
    <a href="${htmlEscape(ctaUrl)}" style="display:inline-block;background:#ff7f02;color:white;text-decoration:none;border-radius:8px;padding:11px 16px;font-weight:700">${htmlEscape(ctaLabel)}</a>
    <p style="font-size:12px;color:#6B7280;margin-top:24px">This email was generated by SandPro OMP. Notification preferences are managed in the app admin settings.</p>
  </div>
`;
