-- SandPro OMP seed data is intentionally empty.
--
-- Do not seed demo objectives, messages, subtasks, files, objective updates, or
-- notifications into customer-facing environments. Profiles and org chart data
-- should be managed through explicit user/admin workflows or dedicated scripts.
